name: Merge Prov Users
on:
  schedule:
    - cron: "0 */1 * * *"
jobs:
  merge:
    name: merge
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run remove-prov-acounts.ts
