name: Merge Prov Users
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  merge:
    name: Merge
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      - name: test
        run: ls -la
      - name: Remove provisional accounts
        run: bun run remove-prov-accounts.ts

