name: Merge Prov Users
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  merge:
    name: Merge
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      - name: Remove provisional acounts
        run: |
          export NODE_TLS_REJECT_UNAUTHORIZED=0
          bun run remove-prov-acounts.ts

